<a href="https://colab.research.google.com/github/Mangai2024/Mangai2024/blob/main/Flight_Price_Category_Analysing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#import pandas libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [2]:
#Load Data
df=pd.read_csv("//content/Flight_Ticket_Prediction_Dataset.csv")

In [3]:
df.head()

Unnamed: 0   airline   flight source_city departure_time stops  \
0           0  SpiceJet  SG-8709       Delhi        Evening  zero   
1           1  SpiceJet  SG-8157       Delhi  Early_Morning  zero   
2           2   AirAsia   I5-764       Delhi  Early_Morning  zero   
3           3   Vistara   UK-995       Delhi        Morning  zero   
4           4   Vistara   UK-963       Delhi        Morning  zero   

    arrival_time destination_city    class  duration  days_left   price  
0          Night           Mumbai  Economy      2.17        1.0  5953.0  
1        Morning           Mumbai  Economy      2.33        1.0  5953.0  
2  Early_Morning           Mumbai  Economy      2.17        1.0  5956.0  
3      Afternoon           Mumbai  Economy      2.25        1.0  5955.0  
4        Morning           Mumbai  Economy      2.33        1.0  5955.0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39481 entries, 0 to 39480
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Unnamed: 0        39481 non-null  int64  
 1   airline           39480 non-null  object 
 2   flight            39480 non-null  object 
 3   source_city       39480 non-null  object 
 4   departure_time    39480 non-null  object 
 5   stops             39480 non-null  object 
 6   arrival_time      39480 non-null  object 
 7   destination_city  39480 non-null  object 
 8   class             39480 non-null  object 
 9   duration          39480 non-null  float64
 10  days_left         39480 non-null  float64
 11  price             39480 non-null  float64
dtypes: float64(3), int64(1), object(8)
memory usage: 3.6+ MB


In [7]:
df.isnull().sum()

Unnamed: 0          0
airline             1
flight              1
source_city         1
departure_time      1
stops               1
arrival_time        1
destination_city    1
class               1
duration            1
days_left           1
price               1
dtype: int64

In [8]:
df[df.isnull().any(axis=1)]

Unnamed: 0 airline flight source_city departure_time stops  \
39480           3     NaN    NaN         NaN            NaN   NaN   

      arrival_time destination_city class  duration  days_left  price  
39480          NaN              NaN   NaN       NaN        NaN    NaN

In [9]:
df.dropna(inplace=True)

In [10]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [Unnamed: 0, airline, flight, source_city, departure_time, stops, arrival_time, destination_city, class, duration, days_left, price]
Index: []

In [11]:
df.isnull().sum()

Unnamed: 0          0
airline             0
flight              0
source_city         0
departure_time      0
stops               0
arrival_time        0
destination_city    0
class               0
duration            0
days_left           0
price               0
dtype: int64

In [14]:
df=df.drop(["Unnamed: 0", "flight"], axis=1)

In [15]:
df.columns

Index(['airline', 'source_city', 'departure_time', 'stops', 'arrival_time',
       'destination_city', 'class', 'duration', 'days_left', 'price'],
      dtype='object')

In [16]:
#Create price category using quantile based binning
#we will divide price into 3 categories[low, medium, high]
df['price_category'] = pd.qcut(df['price'], q=3, labels=['low', 'medium', 'high'])


In [17]:
df.drop('price', axis=1, inplace=True)

In [22]:
#Encode categorical variables using LabelEncoder
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for col in df.select_dtypes(include=['object']).columns:
  df[col]=le.fit_transform(df[col])

In [23]:
#Split the data into train and test
#We will use price_category as a target variable(y)
x=df.drop('price_category', axis=1)
y=df['price_category']

In [24]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(
    x,y, test_size=0.2, random_state=42

)

In [25]:
#Train a model Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(random_state=42)
model.fit(x_train, y_train)

RandomForestClassifier(random_state=42)

In [ ]:
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

In [32]:
#Evaluate the model
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
y_pred=model.predict(x_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n",  classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.9174265450861195

Classification Report:
               precision    recall  f1-score   support

        high       0.94      0.92      0.93      2639
         low       0.93      0.95      0.94      2752
      medium       0.88      0.88      0.88      2505

    accuracy                           0.92      7896
   macro avg       0.92      0.92      0.92      7896
weighted avg       0.92      0.92      0.92      7896


Confusion Matrix:
 [[2432   40  167]
 [  19 2608  125]
 [ 139  162 2204]]


XGBoost Model for Price Category Prediction

Step 1: Imports

In [6]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


Step 2: Load Data

In [7]:
df = pd.read_csv("//content/Flight_Ticket_Prediction_Dataset.csv")

# Drop unwanted columns
df.drop(columns=['Unnamed: 0', 'flight'], inplace=True)

# Drop rows with missing price
df.dropna(subset=['price'], inplace=True)


**Step 3: Create Price** **Categories**

In [8]:
df['price_category'] = pd.qcut(df['price'], q=3, labels=['low', 'medium', 'high'])


**Step 4: Encode Target (numeric labels for XGBoost)**

In [9]:
le = LabelEncoder()
y_encoded = le.fit_transform(df['price_category'])

# Check numeric labels
print("y_encoded sample:", y_encoded[:10])
print("Class mapping:", le.classes_)


y_encoded sample: [2 2 2 2 2 2 2 2 2 2]
Class mapping: ['high' 'low' 'medium']


**Step 5: Prepare Features and Target**

In [10]:
X = df.drop(['price_category', 'price'], axis=1)  # Features
y = y_encoded  # Target


**Step 6: Encode Categorical Features**

In [11]:
cat_cols = X.select_dtypes(include=['object', 'category']).columns
for col in cat_cols:
    X[col] = LabelEncoder().fit_transform(X[col])


**Step 7: Train-Test Split**

In [12]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


**Step 8: Train XGBoost Classifier**

In [13]:
xgb_model = XGBClassifier(
    objective='multi:softmax',
    num_class=3,
    eval_metric='mlogloss',
    use_label_encoder=False,
    random_state=42
)

xgb_model.fit(X_train, y_train)


/usr/local/lib/python3.12/dist-packages/xgboost/training.py:183: UserWarning: [15:24:22] WARNING: /workspace/src/learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None, num_class=3, ...)

**Step 9: Predictions & Evaluation**

In [14]:
y_pred = xgb_model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))


Accuracy: 0.9225400209891556

Classification Report:
               precision    recall  f1-score   support

           0       0.99      0.96      0.97     20030
           1       0.89      0.93      0.91     20003
           2       0.89      0.88      0.88     19998

    accuracy                           0.92     60031
   macro avg       0.92      0.92      0.92     60031
weighted avg       0.92      0.92      0.92     60031


Confusion Matrix:
 [[19160    25   845]
 [    1 18628  1374]
 [  139  2266 17593]]
